### ISSUE TITLE
npm start is not working...

### ISSUE THREAD

**Issue by Maynak2001** [codebucks27/React-Portfolio-starter-code-files#4]
Starting the development server...

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (C:\Users\19301\OneDrive\Desktop\protfolio_2\node_modules\webpack\lib\util\createHash.js:90:53)
    at NormalModule._initBuildHash (C:\Users\19301\OneDrive\Desktop\protfolio_2\node_modules\webpack\lib\NormalModule.js:386:16)
    at handleParseError (C:\Users\19301\OneDrive\Desktop\protfolio_2\node_modules\webpack\lib\NormalModule.js:434:10)
    at C:\Users\19301\OneDrive\Desktop\protfolio_2\node_modules\webpack\lib\NormalModule.js:466:5
    at C:\Users\19301\OneDrive\Desktop\protfolio_2\node_modules\webpack\lib\NormalModule.js:327:12
    at C:\Users\19301\OneDrive\Desktop\protfolio_2\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (C:\Users\19301\OneDrive\Desktop\protfolio_2\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at iterateNormalLoaders (C:\Users\19301\OneDrive\Desktop\protfolio_2\node_modules\loader-runner\lib\LoaderRunner.js:221:10)
    at C:\Users\19301\OneDrive\Desktop\protfolio_2\node_modules\loader-runner\lib\LoaderRunner.js:236:3
    at runSyncOrAsync (C:\Users\19301\OneDrive\Desktop\protfolio_2\node_modules\loader-runner\lib\LoaderRunner.js:130:11)
    at iterateNormalLoaders (C:\Users\19301\OneDrive\Desktop\protfolio_2\node_modules\loader-runner\lib\LoaderRunner.js:232:2)
    at Array.<anonymous> (C:\Users\19301\OneDrive\Desktop\protfolio_2\node_modules\loader-runner\lib\LoaderRunner.js:205:4)
    at Storage.finished (C:\Users\19301\OneDrive\Desktop\protfolio_2\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:55:16)
    at C:\Users\19301\OneDrive\Desktop\protfolio_2\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:91:9
C:\Users\19301\OneDrive\Desktop\protfolio_2\node_modules\react-scripts\scripts\start.js:19
  throw err;
  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (C:\Users\19301\OneDrive\Desktop\protfolio_2\node_modules\webpack\lib\util\createHash.js:90:53)
    at NormalModule._initBuildHash (C:\Users\19301\OneDrive\Desktop\protfolio_2\node_modules\webpack\lib\NormalModule.js:386:16)
    at C:\Users\19301\OneDrive\Desktop\protfolio_2\node_modules\webpack\lib\NormalModule.js:418:10
    at C:\Users\19301\OneDrive\Desktop\protfolio_2\node_modules\webpack\lib\NormalModule.js:293:13
    at C:\Users\19301\OneDrive\Desktop\protfolio_2\node_modules\loader-runner\lib\LoaderRunner.js:367:11
    at C:\Users\19301\OneDrive\Desktop\protfolio_2\node_modules\loader-runner\lib\LoaderRunner.js:233:18
    at context.callback (C:\Users\19301\OneDrive\Desktop\protfolio_2\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at C:\Users\19301\OneDrive\Desktop\protfolio_2\node_modules\babel-loader\lib\index.js:51:103 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.13.0

**Comment by codebucks27** [comment]
Hey, check new commit your issue should be fixed now. Pull the code or create new clone of this repo.

**Comment by Maynak2001** [comment]
Thank you so much!
